name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  xmake:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: use dev cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "latest"

      - name: config
        run: xmake config -y --mode=releasedbg --toolchain=msvc

      - name: build
        run: xmake build -y -vD

      - name: test
        run: |
          xmake build -y FormatTemplateTests
          xmake run FormatTemplateTests

      - name: get short sha
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV

      - name: bundle
        run: |
          xmake package
          Rename-Item -Path "dist" -NewName "Fallout4RichPresence-${{ env.SHORT_SHA }}"

      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Fallout4RichPresence-${{ env.SHORT_SHA }}
          path: "Fallout4RichPresence-${{ env.SHORT_SHA }}"
