#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace Presence
{
	// mirrors the RE::MARKER_TYPE values we ship artwork for; Presence stays free of RE types
	enum class MarkerType : std::uint32_t
	{
		kCave = 0x00,
		kCity = 0x01,
		kDiamondCity = 0x02,
		kEncampment = 0x03,
		kIndustrial = 0x04,
		kMetro = 0x06,
		kMilitaryBase = 0x07,
		kLandmark = 0x08,
		kOffice = 0x09,
		kRuinsTown = 0x0A,
		kRuinsUrban = 0x0B,
		kSanctuary = 0x0C,
		kSettlement = 0x0D,
		kSewer = 0x0E,
		kVault = 0x0F,
		kAirfield = 0x10,
		kBunkerHill = 0x11,
		kCamper = 0x12,
		kChurch = 0x14,
		kCountryClub = 0x15,
		kCustomHouse = 0x16,
		kDriveIn = 0x17,
		kElevatedHighway = 0x18,
		kFaneuilHall = 0x19,
		kFarm = 0x1A,
		kFillingStation = 0x1B,
		kForest = 0x1C,
		kGoodNeighbor = 0x1D,
		kGraveyard = 0x1E,
		kHospital = 0x1F,
		kIndustrialDome = 0x20,
		kIndustrialStacks = 0x21,
		kInstitute = 0x22,
		kIrishPride = 0x23,
		kJunkyard = 0x24,
		kObservatory = 0x25,
		kPier = 0x26,
		kPondOrLake = 0x27,
		kQuarry = 0x28,
		kRadioactiveArea = 0x29,
		kRadioTower = 0x2A,
		kSalem = 0x2B,
		kSchool = 0x2C,
		kShipwreck = 0x2D,
		kSubmarine = 0x2E,
		kSwanPond = 0x2F,
		kSynthHead = 0x30,
		kTown = 0x31,
		kBOS = 0x32,
		kBrownstone = 0x33,
		kBunker = 0x34,
		kCastle = 0x35,
		kSkyscraper = 0x36,
		kLibertalia = 0x37,
		kLowrise = 0x38,
		kMinutemen = 0x39,
		kPoliceStation = 0x3A,
		kPrydwen = 0x3B,
		kRailroadFaction = 0x3C,
		kRailroad = 0x3D,
		kSatellite = 0x3E,
		kSentinel = 0x3F,
		kUSSConstitution = 0x40,
		kMechanist = 0x41,
		kRaiderSettlement = 0x42,
		kVassalSettlement = 0x43,
		kPotentialVassalSettlement = 0x44,
		kBottlingPlant = 0x45,
		kGalactic = 0x46,
		kKiddieKingdom = 0x48,
		kMonorail = 0x49,
		kRides = 0x4A,
		kSafari = 0x4B,
		kWildWest = 0x4C,
		kDisciples = 0x4E
	};

	struct MarkerAsset
	{
		MarkerType       type;
		std::string_view key;
	};

	// curated: a type absent here falls back to the configured default image
	inline constexpr std::array kMarkerAssets{
		MarkerAsset{ MarkerType::kCave, "marker_cave" },
		MarkerAsset{ MarkerType::kCity, "marker_city" },
		MarkerAsset{ MarkerType::kDiamondCity, "marker_diamondcity" },
		MarkerAsset{ MarkerType::kEncampment, "marker_encampment" },
		MarkerAsset{ MarkerType::kIndustrial, "marker_industrial" },
		MarkerAsset{ MarkerType::kMetro, "marker_metro" },
		MarkerAsset{ MarkerType::kMilitaryBase, "marker_militarybase" },
		MarkerAsset{ MarkerType::kLandmark, "marker_landmark" },
		MarkerAsset{ MarkerType::kOffice, "marker_office" },
		MarkerAsset{ MarkerType::kRuinsTown, "marker_ruinstown" },
		MarkerAsset{ MarkerType::kRuinsUrban, "marker_ruinsurban" },
		MarkerAsset{ MarkerType::kSanctuary, "marker_sanctuary" },
		MarkerAsset{ MarkerType::kSettlement, "marker_settlement" },
		MarkerAsset{ MarkerType::kSewer, "marker_sewer" },
		MarkerAsset{ MarkerType::kVault, "marker_vault" },
		MarkerAsset{ MarkerType::kAirfield, "marker_airfield" },
		MarkerAsset{ MarkerType::kBunkerHill, "marker_bunkerhill" },
		MarkerAsset{ MarkerType::kCamper, "marker_camper" },
		MarkerAsset{ MarkerType::kChurch, "marker_church" },
		MarkerAsset{ MarkerType::kCountryClub, "marker_countryclub" },
		MarkerAsset{ MarkerType::kCustomHouse, "marker_customhouse" },
		MarkerAsset{ MarkerType::kDriveIn, "marker_drivein" },
		MarkerAsset{ MarkerType::kElevatedHighway, "marker_highway" },
		MarkerAsset{ MarkerType::kFaneuilHall, "marker_faneuilhall" },
		MarkerAsset{ MarkerType::kFarm, "marker_farm" },
		MarkerAsset{ MarkerType::kFillingStation, "marker_fillingstation" },
		MarkerAsset{ MarkerType::kForest, "marker_forest" },
		MarkerAsset{ MarkerType::kGoodNeighbor, "marker_goodneighbor" },
		MarkerAsset{ MarkerType::kGraveyard, "marker_graveyard" },
		MarkerAsset{ MarkerType::kHospital, "marker_hospital" },
		MarkerAsset{ MarkerType::kIndustrialDome, "marker_industrialdome" },
		MarkerAsset{ MarkerType::kIndustrialStacks, "marker_industrialstacks" },
		MarkerAsset{ MarkerType::kInstitute, "marker_institute" },
		MarkerAsset{ MarkerType::kIrishPride, "marker_irishpride" },
		MarkerAsset{ MarkerType::kJunkyard, "marker_junkyard" },
		MarkerAsset{ MarkerType::kObservatory, "marker_observatory" },
		MarkerAsset{ MarkerType::kPier, "marker_pier" },
		MarkerAsset{ MarkerType::kPondOrLake, "marker_water" },
		MarkerAsset{ MarkerType::kQuarry, "marker_quarry" },
		MarkerAsset{ MarkerType::kRadioactiveArea, "marker_radioactive" },
		MarkerAsset{ MarkerType::kRadioTower, "marker_radiotower" },
		MarkerAsset{ MarkerType::kSalem, "marker_salem" },
		MarkerAsset{ MarkerType::kSchool, "marker_school" },
		MarkerAsset{ MarkerType::kShipwreck, "marker_shipwreck" },
		MarkerAsset{ MarkerType::kSubmarine, "marker_submarine" },
		MarkerAsset{ MarkerType::kSwanPond, "marker_swanpond" },
		MarkerAsset{ MarkerType::kSynthHead, "marker_synthhead" },
		MarkerAsset{ MarkerType::kTown, "marker_town" },
		MarkerAsset{ MarkerType::kBOS, "marker_bos" },
		MarkerAsset{ MarkerType::kBrownstone, "marker_brownstone" },
		MarkerAsset{ MarkerType::kBunker, "marker_bunker" },
		MarkerAsset{ MarkerType::kCastle, "marker_castle" },
		MarkerAsset{ MarkerType::kSkyscraper, "marker_skyscraper" },
		MarkerAsset{ MarkerType::kLibertalia, "marker_libertalia" },
		MarkerAsset{ MarkerType::kLowrise, "marker_lowrise" },
		MarkerAsset{ MarkerType::kMinutemen, "marker_minutemen" },
		MarkerAsset{ MarkerType::kPoliceStation, "marker_policestation" },
		MarkerAsset{ MarkerType::kPrydwen, "marker_prydwen" },
		MarkerAsset{ MarkerType::kRailroadFaction, "marker_railroad" },
		MarkerAsset{ MarkerType::kRailroad, "marker_railroad" },
		MarkerAsset{ MarkerType::kSatellite, "marker_satellite" },
		MarkerAsset{ MarkerType::kSentinel, "marker_sentinel" },
		MarkerAsset{ MarkerType::kUSSConstitution, "marker_constitution" },
		MarkerAsset{ MarkerType::kMechanist, "marker_mechanist" },
		MarkerAsset{ MarkerType::kRaiderSettlement, "marker_raidersettlement" },
		MarkerAsset{ MarkerType::kVassalSettlement, "marker_vassalsettlement" },
		MarkerAsset{ MarkerType::kPotentialVassalSettlement, "marker_potentialvassal" },
		MarkerAsset{ MarkerType::kBottlingPlant, "marker_bottlingplant" },
		MarkerAsset{ MarkerType::kGalactic, "marker_galactic" },
		MarkerAsset{ MarkerType::kKiddieKingdom, "marker_kiddiekingdom" },
		MarkerAsset{ MarkerType::kMonorail, "marker_monorail" },
		MarkerAsset{ MarkerType::kRides, "marker_rides" },
		MarkerAsset{ MarkerType::kSafari, "marker_safari" },
		MarkerAsset{ MarkerType::kWildWest, "marker_wildwest" },
		MarkerAsset{ MarkerType::kDisciples, "marker_disciples" }
	};

	[[nodiscard]] std::string_view MarkerAssetKey(std::uint32_t a_markerType) noexcept;
}
